config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  devise_for :users, controllers: { confirmations: 'confirmations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/admin", to: "admin#index", as: "admin_path"
  put "/togle-status", to: "admin#toggle_account_status", as: "toggle_account_status_path"
  put "/toggle-admin", to: "admin#toggle_account_admin", as: "toggle_account_admin_path"
  get "/next", to: "stocks#next", as: "stocks_next_path"
  get "/inactive-account", to:"inactive_account#index"
  # Defines the root path route ("/")
  # root "articles#index"
  root "stocks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/stock.rb
class Stock < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :stocks

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    before_action :check_admin

    def index
        @users = User.all
    end

    def toggle_account_status
        @user = User.find(params[:id])
        @user.update(is_active: !@user.is_active)
        redirect_to admin_path_url and return
    end

    def toggle_account_admin
        @user = User.find(params[:id])
        @user.update(admin: !@user.admin)
        redirect_to admin_path_url and return
    end

    private
    def check_admin
        if !current_user.admin?
            redirect_to "/"
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name, :first_name])
  end
  
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController

end

app/controllers/inactive_account_controller.rb
class InactiveAccountController < ApplicationController
    def index
        @admins = User.find_by_admin(true)
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: %i[ show edit update destroy ]
  before_action :check_admin
  before_action :set_exchange, only: %i[new next create edit update]
  before_action :check_active

  # GET /stocks or /stocks.json
  def index
    @stocks = current_user.stocks
  end

  # GET /stocks/1 or /stocks/1.json
  def show
  end

  def next
    split_str = params[:symbol].split('+')
    @symbol = split_str[0]
    @name = split_str[1] 
    @qoute = @client.quote(@symbol)
    @stock = Stock.new
  end

  # GET /stocks/new
  def new
    @symbols = @client.ref_data_symbols
  end

  # GET /stocks/1/edit
  def edit
    @qoute = @client.quote(@stock[:symbol])
  end

  # POST /stocks or /stocks.json
  def create
    @stock = current_user.stocks.new(stock_params)
    current_user.balance -= (@stock.count * @stock.value)

    if current_user.balance < 0
      flash.now[:alert] = "Insufficient Balance"
      redirect_to :back
      return
    else
      current_user.save
    end
    

    respond_to do |format|
      if @stock.save
        format.html { redirect_to stock_url(@stock), notice: "Stock was successfully created." }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1 or /stocks/1.json
  def update
    stock = current_user.stocks.find(params[:id])
    qoute = @client.quote(stock[:symbol])
    stock.value = qoute.latest_price
    stock.count = params[:commit] == "Buy" ? stock.count + params[:change][:count_delta].to_i : stock.count - params[:change][:count_delta].to_i

    current_user.balance = params[:commit] == "Buy" ? current_user.balance.to_i - (params[:change][:count_delta].to_i * qoute.latest_price).to_i : current_user.balance.to_i + (params[:change][:count_delta].to_i * qoute.latest_price).to_i

    if stock.count < 0
      flash.now[:alert] = "Insufficient Inventory"
      return
    end
    if params[:commit] == "Buy" && current_user.balance < 0
      flash.now[:alert] = "Insufficient Balance"
      return
    else
      current_user.save
    end


    respond_to do |format|
      if stock.save
        format.html { redirect_to stock_url(@stock), notice: "Stock was successfully updated." }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1 or /stocks/1.json
  def destroy
    @stock.destroy

    respond_to do |format|
      format.html { redirect_to stocks_url, notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def check_active
      if (!current_user.is_active)
        redirect_to "/inactive-account"
      end
    end

    def check_admin
      if (current_user.admin)
        redirect_to "/admin"
      end
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stock_params
      params.require(:stock).permit(:stock_name, :symbol, :desc, :value, :count)
    end


    def set_exchange
      @client = IEX::Api::Client.new ({
        publishable_token: ENV['PUBLISHABLE_TOKEN'],
        secret_token: ENV['SECRET_TOKEN'],
        endpoint: 'https://cloud.iexapis.com/v1'
      }
      )
    end
end

app/helpers/admin/transactions_helper.rb
module Admin::TransactionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/admin/index.html.erb
<h1>Users</h1>

<div id="users" class="collection">
  <% @users.each do |user| %>
    <li class="collection-item">
        <div class="user-item">
          <div>
          <h5><%= user.first_name%> <%= user.last_name%></h5>
          <span>Email: <%= user.email%></span>
          <br />
          <span>Balance: <%= user.balance%></span>
          <br />
          <span>Account Status: <% if user.is_active %> <span class="green-text"> Active </span> <%else%> <span class="red-text"> Inactive </span> <%end%></span>
          <br />
          <span>Account Type: <% if user.admin %> Admin <%else%> User <%end%></span>
          </div>
          <div style="display:flex; flex-direction:column; gap:1rem;">
            <%= button_to "Toggle Status", toggle_account_status_path_path(id:user.id), method: :put, class:"btn" %>
            <%= button_to "Toggle Admin", toggle_account_admin_path_path(id:user.id), :disabled => user.id == current_user.id, method: :put, class:"btn red darken-1"%>
          </div>
        </div>
    </li>
  <% end %>
</div>

app/views/inactive_account/index.html.erb
<div style="height:60vh; display:flex; align-items:center;">
    <div>
    <h2>Account <%=current_user.first_name%> <%=current_user.last_name%> is inactive</h2>
    <p>Please contact an Administrator for assistance</p>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<nav>
<div class="nav-wrapper teal lighten-2" style="padding:0px 10px; z-index:0;">
  <a href="/" class="brand-logo">Stock App</a>
  <ul id="nav-mobile" class="right hide-on-med-and-down">
    <% if user_signed_in? %>
      <li><a href="/"> Manage <%if !current_user.admin %> Stocks <%else%> Users <%end%></a></li>
      <li><%= link_to "Profile", edit_user_registration_path %></li>
      <li><%= link_to "Sign Out", destroy_user_session_path %></li>
    <%end%>
  </ul>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <p style="color: green"><%= notice %></p>
      <p style="color: red"><%= alert %></p>

      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_form.html.erb
<%= form_with(model: stock) do |form| %>
  <% if stock.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
        <% stock.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :symbol, style: "display: block" %>
    <%= form.text_field :symbol %>
  </div>

  <div>
    <%= form.label :desc, style: "display: block" %>
    <%= form.text_area :desc %>
  </div>

  <div>
    <%= form.label :value, style: "display: block" %>
    <%= form.number_field :value %>
  </div>

  <div>
    <%= form.label :count, style: "display: block" %>
    <%= form.number_field :count %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/_stock.html.erb
<div id="<%= dom_id stock %>">
    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= stock.stock_name %></span>
          <ul>
            <li>Symbol: <%= stock.symbol %></li>
            <li>Purchase Value: USD <%= stock.value %></li>
            <li>Shares: <%= stock.count %></li>
            <li>Total Value at Purchase: USD <%= number_to_currency((stock.count * stock.value ), delimiter: '', unit: '')%></li>
          </ul>
        </div>
        <div class="card-action valign-wrapper" style="gap:1rem;">
         <%= button_to "Buy/Sell", edit_stock_path(stock.id), class:"waves-effect waves-light btn", method: :get %>
          <% if stock.count < 1 %>
            <%= button_to "Remove", stock_path(stock.id), class:"waves-effect waves-light btn red", method: :delete %>
          <%end%>
        
        </div>
      </div>
    </div>
</div>

app/views/stocks/edit.html.erb
<h1>Buy/Sell Stock</h1>

      <ul class="collection with-header">
        <li class="collection-header"><h4><%=@stock.stock_name%></h4></li>
        <li class="collection-item">Symbol: <%=@stock.symbol%></li>
        <li class="collection-item">Purchase Price: <%=@stock.value%></li>
        <li class="collection-item">Latest Price: <%=@qoute.latest_price%></li>
        <li class="collection-item">Inventory: <%=@stock.count%></li>
        <li class="collection-item">Total Value: <%=@stock.count * @qoute.latest_price%></li>
      </ul> 
      <%= form_for :change, method: :put, url: stock_path do |f|%>
        <%= f.number_field :stock_id, value: @stock.id, readonly: true, class:"hide"%>
        <%=label_tag "Amount"%>
        <%=f.number_field :count_delta %>
          <%=f.submit "Buy", class:"waves-effect waves-light btn"%>
          <%=f.submit "Sell", class:"waves-effect waves-light btn red"%>
      <%end%>
<br>

<div>
  <%= link_to "Show this stock", @stock %> |
  <%= link_to "Back to stocks", stocks_path %>
</div>

app/views/stocks/index.html.erb
<div class="row valign-wrapper" style="justify-content:space-between">
  <div class="col s12 valign-wrapper" style="justify-content:space-between">
    <div class="left-align" style="padding:0px 5px;">
      <h1>Your Portfolio</h1>
      <div style="padding:0px 10px;">
      <h5><%="#{current_user.first_name} #{current_user.last_name}"%></h5>
      <h5>Balance: <%= current_user.balance%> USD</h5>
      </div>
    </div>
    <div class="center-align">
      <%= link_to "+", new_stock_path, class:"btn-floating btn-large waves-effect waves-light red", data:{turbo:false} %>
    </div>
  </div>
</div>

<div class="row">
  <div id="stocks">
    <% @stocks.each do |stock| %>
      <%= render stock %>
    <% end %>
  </div>
</div>

app/views/stocks/new.html.erb
<div class="row">
<h2>Buy Stocks</h2>   
</div>
<div class="row">
<form action="/next/" accept-charset="UTF-8" method="get" class="input-field col s12">
    <%=@market%>
    <select name="symbol">
      <%= @symbols.each do |symbol|%>
        <option value="<%=symbol.symbol%>+<%=symbol.name%>"><%=symbol.name%></option>
      <%end%>
    </select>
    <label>Select Stocks</label>
    <div class="valign-wrapper" style="gap:1rem;">
    <%= link_to "Back", stocks_path, class:"waves-effect waves-light btn red" %>
    <button class="waves-effect waves-light btn">See Details</button>
    </div>
</form>
</div>
</div>

app/views/stocks/next.html.erb
<div class="valign-wrapper" style="height:70vh; display:flex; flex-direction:column; align-items:start">
<h3>Buy Stock</h3>
<h5>Balance: <%= current_user.balance%> USD</h5>

<%=form_for @stock do |f|%>
    <%= label_tag :stock_name%>
    <%= f.text_field :stock_name, class: 'black-text',value: @name, readonly: true %>
    
    <%= label_tag :symbol%>
    <%= f.text_field :symbol, class:'black-text',value: @symbol,  readonly: true%>

    <%= label_tag "Current Market Price in USD"%>
    <%= f.text_field :value, class: 'black-text',value: number_to_currency(@qoute.latest_price, delimiter: '', unit: ''),  readonly: true %>
    <%= label_tag "Change"%>
    <%= text_field_tag :change, @qoute.change_percent, class: @qoute.change_percent.negative? ? "red-text" : "green-text",  readonly: true%>
    <%= label_tag "Quantity"%>
    <%= f.number_field :count, class: 'number_field' %>
    <%= link_to "Cancel", stocks_path, class:"waves-effect waves-light btn red" %>
    <%= f.submit "Buy Stock", class:"waves-effect waves-light btn"%>
<%end%>
</div>

app/views/stocks/show.html.erb
<h5>Balance: <%= current_user.balance%> USD</h5>

<%= render @stock %>

<div>
  <%= button_to "Back to stocks", stocks_path, class:"waves-effect waves-light btn", method: :get %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>